from fastapi import APIRouter
import logging
import traceback
from .models import AgentRequest, AgentResponse, AgentState
from .graph import get_agent_graph
from langchain.messages import HumanMessage, AIMessage
import json
from types import NoneType


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
agent_router = APIRouter()

@agent_router.post("/invoke", response_model=AgentResponse)
async def invoke_request(request: AgentRequest) -> AgentResponse:
    """API route to invoke the agent with the given request"""

    try:
        if isinstance(request, dict):
            request = AgentRequest(query=request.get("query"), session_id=request.get("session_id"), organization_id=request.get("organization_id"), user_id=request.get("user_id"))
        else:
            request = AgentRequest(**request.dict())
        state = AgentState(messages=[HumanMessage(content=request.query)], organization_id=request.organization_id, session_id=request.session_id, organization_name=request.organization_name, user_id=request.user_id)

        result = await invoke_agent_graph(state)

        ai_message = get_AIMessage_from_response(result) or "No response generated by the agent."
        # ai_message = result["messages"]
        # for ele in ai_message:
        #     print(type(ele) ,  ele.content)
        token_usage = get_token_usages_from_response(result)
        return AgentResponse(response=ai_message, token_usage=token_usage)
    except Exception as e:
        logger.error(f"Error invoking agent: {e}")
        logger.error(traceback.format_exc())
        return AgentResponse(response=f"Error processing query: {str(e)}", token_usage=None)


async def invoke_agent_graph(state: AgentState) -> AgentState:
    """Invoke the agent with the given state. This is the main function that will be called from the API route."""
    try:
        agent = await get_agent_graph()

        # config for graphs' short term memory (checkpoint saver)
        thread_id = state.get("session_id") or state.get("user_id")
        user_memory_config = {"configurable": {"thread_id": f"{thread_id}"}}

        result = await agent.ainvoke(state, user_memory_config)
        messages = result["messages"] if result and "messages" in result else []
 
        return AgentState(messages=messages, organization_id=state["organization_id"], session_id=state["session_id"], organization_name=state.get("organization_name"), user_id=state.get("user_id")) 
    except Exception as e:
        logger.error(f"Error invoking agent graph: {e}")
        logger.error(traceback.format_exc())
        return AgentState(messages=[HumanMessage(content="Not Processed. Error occurred.")], organization_id=state["organization_id"], session_id=state["session_id"], organization_name=state.get("organization_name"))


def get_AIMessage_from_response(res: str) -> str:
    """Extract the AIMessage content from the agent response"""
    try:
        response = res["messages"]
        for ele in reversed(response):
            if type(ele) == AIMessage and ele.content and not isinstance(ele.content, NoneType):
                return str(ele.content)
        for ele in reversed(response):
            content = getattr(ele, "content", None)
            if content and not isinstance(content, NoneType):
                return str(content)
        return "No response generated by the agent."
    except Exception as e:
        logger.error(f"Error parsing agent response: {e}")
        logger.error(traceback.format_exc())
        return str(res) if res is not None else "No response generated by the agent."


def get_token_usages_from_response(res:str) -> str:
    """Extract token usage information from the agent response if available"""
    try:
        response = res["messages"]
        for ele in response:
            if hasattr(ele, "response_metadata") and ele.response_metadata and "token_usage" in ele.response_metadata:
                return str(ele.response_metadata["token_usage"])
        return None
    except Exception as e:
        logger.error(f"Error parsing token usage from agent response: {e}")
        logger.error(traceback.format_exc())
        return None
